config/routes.rb
CkTest::Application.routes.draw do
  filter :locale
  
  resources :things
  
  resources :products
  
  constraints(Subdomain) do  
    root :to => 'things#index'    
  end

  root :to => 'products#index'
  

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name
end

app/models/thing.rb
class Thing < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :set_locale
  protect_from_forgery
  layout 'application'
  def set_locale
    # if params[:locale] is nil then I18n.default_locale will be used
    I18n.locale = params[:locale]
  end  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end
  
  def new
    @product = Product.new
  end
  
  def create
    @product = Product.new(params[:product])
    if @product.save
      flash[:notice] = "Successfully created product."
      redirect_to products_url
    else
      render :action => 'new'
    end
  end
end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  def index
    @things = Thing.all
  end
  
  def new
    @thing = Thing.new
  end
  
  def create
    @thing = Thing.new(params[:thing])
    if @thing.save
      flash[:notice] = "Successfully created thing."
      redirect_to things_url
    else
      render :action => 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { page_title.to_s }
    @show_title = show_title
  end
  
  def show_title?
    @show_title
  end
  
  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end
  
  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/things_helper.rb
module ThingsHelper
end

app/helpers/url_helper.rb
module UrlHelper  
  def with_subdomain(subdomain)  
    subdomain = (subdomain || "")  
    subdomain += "." unless subdomain.empty?  
    [subdomain, request.domain, request.port_string].join  
  end  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) || "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/index.html.erb
<% title t(:products) %>

<table>
  <tr>
    <th>Name</th>
  </tr>
  <% for product in @products %>
    <tr>
      <td><%= product.name %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to t(:new_product), new_product_path %></p>

app/views/products/new.html.erb
<% title "New Product" %>

<%= form_for @product do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p><%= f.submit %></p>
<% end %>


<p><%= link_to "Back to List", products_path %></p>

app/views/things/index.html.erb
<% title t(:things) %>

<table>
  <tr>
    <th>Name</th>
  </tr>
  <% for thing in @things %>
    <tr>
      <td><%= thing.name %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to t(:new_thing), new_thing_path %></p>

app/views/things/new.html.erb
<% title "New Thing" %>

<%= form_for @thing do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p><%= f.submit %></p>
<% end %>


<p><%= link_to "Back to List", things_path %></p>